// Generated by BUCKLESCRIPT VERSION 4.0.14, PLEASE EDIT WITH CARE
'use strict';

var Belt_List = require("bs-platform/lib/js/belt_List.js");

function songAdapter(param) {
  var features = param[1];
  var track = param[0];
  return /* record */[
          /* id */track[/* id */4],
          /* attrs : record */[
            /* popularity */track[/* popularity */3],
            /* danceability */features[/* danceability */1],
            /* energy */features[/* energy */2],
            /* speechiness */features[/* speechiness */3],
            /* acousticness */features[/* acousticness */4],
            /* instrumentalness */features[/* instrumentalness */5],
            /* liveness */features[/* liveness */6],
            /* valence */features[/* valence */7],
            /* tempo */features[/* tempo */8],
            /* loudness */features[/* loudness */9]
          ],
          /* display : record */[
            /* title */track[/* name */2],
            /* artists */Belt_List.fromArray(track[/* artists */1]),
            /* albumName */track[/* albumName */0]
          ]
        ];
}

function getValueName(value) {
  switch (value) {
    case 0 : 
        return "Popularity";
    case 1 : 
        return "Danceability";
    case 2 : 
        return "Energy";
    case 3 : 
        return "Speechiness";
    case 4 : 
        return "Acousticness";
    case 5 : 
        return "Instrumentalness";
    case 6 : 
        return "Liveness";
    case 7 : 
        return "Valence";
    case 8 : 
        return "Tempo";
    case 9 : 
        return "Loudness";
    
  }
}

function getSearchTypeName(searchType) {
  switch (searchType) {
    case 0 : 
        return "Album";
    case 1 : 
        return "Artist";
    case 2 : 
        return "Playlist";
    
  }
}

function searchItemAdapter(fromJSON) {
  return /* record */[
          /* name */fromJSON[/* name */1],
          /* id */fromJSON[/* id */0],
          /* artists */fromJSON[/* artists */2],
          /* image */fromJSON[/* image */3]
        ];
}

exports.songAdapter = songAdapter;
exports.getValueName = getValueName;
exports.getSearchTypeName = getSearchTypeName;
exports.searchItemAdapter = searchItemAdapter;
/* No side effect */
