// Generated by BUCKLESCRIPT VERSION 4.0.14, PLEASE EDIT WITH CARE
'use strict';

var $$Array = require("bs-platform/lib/js/array.js");
var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var Data$ReactTemplate = require("./Data.bs.js");
var Search$ReactTemplate = require("./Search.bs.js");
var SpotifyAPI$ReactTemplate = require("./SpotifyAPI.bs.js");
var SearchItems$ReactTemplate = require("./SearchItems.bs.js");

require("./Picker.css");

var component = ReasonReact.reducerComponent("Picker");

function make(handleItemClick, handleSearchSubmit, _children) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (self) {
              var handleSubmit = function (q) {
                if (q.length !== 0) {
                  Curry._1(handleSearchSubmit, /* () */0);
                  SpotifyAPI$ReactTemplate.Request[/* searchHack */11](q).then((function (fromJSON) {
                          return Promise.resolve(Curry._1(self[/* send */3], /* SetItems */[$$Array.map(Data$ReactTemplate.searchItemAdapter, fromJSON)]));
                        }));
                  return /* () */0;
                } else {
                  return 0;
                }
              };
              var handleClick = function (searchItem, _event) {
                Curry._1(self[/* send */3], /* SetItems */[/* array */[]]);
                return Curry._1(handleItemClick, searchItem);
              };
              return React.createElement("div", {
                          className: "Picker"
                        }, React.createElement("div", {
                              className: "SearchBox"
                            }, ReasonReact.element(undefined, undefined, Search$ReactTemplate.make(handleSubmit, /* array */[]))), ReasonReact.element(undefined, undefined, SearchItems$ReactTemplate.make(self[/* state */1][/* items */0], handleClick, /* array */[])));
            }),
          /* initialState */(function (param) {
              return /* record */[/* items : array */[]];
            }),
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */(function (action, _state) {
              return /* Update */Block.__(0, [/* record */[/* items */action[0]]]);
            }),
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

exports.component = component;
exports.make = make;
/*  Not a pure module */
