// Generated by BUCKLESCRIPT VERSION 4.0.14, PLEASE EDIT WITH CARE
'use strict';

var $$Array = require("bs-platform/lib/js/array.js");
var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var ReasonReact = require("reason-react/src/ReasonReact.js");

require("./SearchItems.css");

var component = ReasonReact.statelessComponent("SearchItems");

function make(items, handleClick, _children) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (_self) {
              return React.createElement("ul", {
                          className: "Container"
                        }, $$Array.map((function (item) {
                                return React.createElement("li", {
                                            key: item[/* id */1],
                                            className: "Item",
                                            onClick: Curry._1(handleClick, item)
                                          }, React.createElement("img", {
                                                className: "Image",
                                                src: item[/* image */3]
                                              }), React.createElement("div", {
                                                className: "Name"
                                              }, item[/* name */0]), React.createElement("div", {
                                                className: "Artists"
                                              }, item[/* artists */2].join(",")));
                              }), items));
            }),
          /* initialState */component[/* initialState */10],
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */component[/* reducer */12],
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

exports.component = component;
exports.make = make;
/*  Not a pure module */
