// Generated by BUCKLESCRIPT VERSION 4.0.14, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var ReasonReact = require("reason-react/src/ReasonReact.js");

var component = ReasonReact.statelessComponent("SongTableHeader");

function make(valueName, onHeaderClick, _children) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (_self) {
              return React.createElement("thead", undefined, React.createElement("tr", undefined, React.createElement("th", {
                                  onClick: Curry._1(onHeaderClick, /* Value */0)
                                }, "Rank"), React.createElement("th", {
                                  onClick: Curry._1(onHeaderClick, /* Value */0)
                                }, valueName), React.createElement("th", {
                                  onClick: Curry._1(onHeaderClick, /* Title */1)
                                }, "Title"), React.createElement("th", {
                                  onClick: Curry._1(onHeaderClick, /* Artists */2)
                                }, "Artist"), React.createElement("th", {
                                  onClick: Curry._1(onHeaderClick, /* Album */3)
                                }, "Album")));
            }),
          /* initialState */component[/* initialState */10],
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */component[/* reducer */12],
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

exports.component = component;
exports.make = make;
/* component Not a pure module */
