// Generated by BUCKLESCRIPT VERSION 4.0.14, PLEASE EDIT WITH CARE
'use strict';

var $$Array = require("bs-platform/lib/js/array.js");
var React = require("react");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var Data$ReactTemplate = require("./Data.bs.js");
var SongTableRow$ReactTemplate = require("./SongTableRow.bs.js");
var SongTableHeader$ReactTemplate = require("./SongTableHeader.bs.js");

var component = ReasonReact.statelessComponent("SongTable");

function valueToStr(value, songAttrs) {
  switch (value) {
    case 0 : 
        return String(songAttrs[/* popularity */0]);
    case 1 : 
        return String(songAttrs[/* danceability */1]);
    case 2 : 
        return String(songAttrs[/* energy */2]);
    case 3 : 
        return String(songAttrs[/* speechiness */3]);
    case 4 : 
        return String(songAttrs[/* acousticness */4]);
    case 5 : 
        return String(songAttrs[/* instrumentalness */5]);
    case 6 : 
        return String(songAttrs[/* liveness */6]);
    case 7 : 
        return String(songAttrs[/* valence */7]);
    case 8 : 
        return String(songAttrs[/* tempo */8]);
    case 9 : 
        return String(songAttrs[/* loudness */9]);
    
  }
}

function make(songs, value, onHeaderClick, _children) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (_self) {
              return React.createElement("table", undefined, ReasonReact.element(undefined, undefined, SongTableHeader$ReactTemplate.make(Data$ReactTemplate.getValueName(value), onHeaderClick, /* array */[])), React.createElement("tbody", undefined, $$Array.map((function (param) {
                                    var song = param[1];
                                    return ReasonReact.element(song[/* id */0], undefined, SongTableRow$ReactTemplate.make(param[0] + 1 | 0, valueToStr(value, song[/* attrs */1]), song[/* display */2][/* title */0], song[/* display */2][/* artists */1], song[/* display */2][/* albumName */2], /* array */[]));
                                  }), songs)));
            }),
          /* initialState */component[/* initialState */10],
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */component[/* reducer */12],
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

exports.component = component;
exports.valueToStr = valueToStr;
exports.make = make;
/* component Not a pure module */
