// Generated by BUCKLESCRIPT VERSION 4.0.14, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");

function flip(f, a, b) {
  return Curry._2(f, b, a);
}

exports.flip = flip;
/* No side effect */
